[package]
name = "tree-sitter-inspector"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
# Core parser
tree-sitter = { version = "0.26.10", features = ["wasm"] }

wasmtime = { version = "=36.0.12", default-features = true, features = ["cache"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }

once_cell = "1.21.4"
log = "0.4"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
